export interface LocationData {
  slug: string;
  name: string;
  region: string;
  description: string;
  nearbyAreas: string[];
  image: string;
  metaDescription: string;
}

export const locationsData: Record<string, LocationData> = {
  'painters-in-geelong': {
    slug: 'painters-in-geelong',
    name: 'Geelong',
    region: 'Geelong',
    description: 'Norm Painting is based in Geelong and proudly serves the entire Geelong region. From Victorian terraces in Newtown to modern homes in Armstrong Creek, we deliver premium interior and exterior painting with a 7-year workmanship warranty.',
    nearbyAreas: ['Newtown', 'Geelong West', 'Belmont', 'Highton', 'Waurn Ponds', 'Armstrong Creek', 'Torquay', 'Ocean Grove', 'Lara', 'Corio'],
    image: '/projects/project-06.jpg',
    metaDescription: 'Professional painters in Geelong. Interior & exterior house painting, roof painting, and commercial painting with a 7-year warranty — Norm Painting.',
  },
  'painters-in-geelong-west': {
    slug: 'painters-in-geelong-west',
    name: 'Geelong West',
    region: 'Geelong',
    description: 'Geelong West is home to some of the region\'s most charming period homes and character properties. Norm Painting specialises in restoring and refreshing these homes with period-appropriate colours and premium finishes that honour their heritage.',
    nearbyAreas: ['Geelong CBD', 'Newtown', 'Manifold Heights', 'Drumcondra', 'Herne Hill', 'Hamlyn Heights', 'Belmont', 'Highton'],
    image: '/projects/project-30.jpg',
    metaDescription: 'Painters in Geelong West. Heritage and modern home painting, interior & exterior, with free quotes — Norm Painting.',
  },
  'painters-in-bellarine': {
    slug: 'painters-in-bellarine',
    name: 'Bellarine Peninsula',
    region: 'Geelong',
    description: 'From Ocean Grove to Portarlington, we service the entire Bellarine Peninsula. Coastal properties need specialist coatings that resist salt air, moisture, and UV exposure — and that\'s exactly what we provide with our premium exterior painting systems.',
    nearbyAreas: ['Ocean Grove', 'Barwon Heads', 'Queenscliff', 'Portarlington', 'Drysdale', 'Leopold', 'St Leonards', 'Indented Head'],
    image: '/projects/project-05.jpg',
    metaDescription: 'Painters on the Bellarine Peninsula. Coastal-grade exterior painting for Ocean Grove, Barwon Heads, Queenscliff & surrounds — Norm Painting.',
  },
  'painters-in-south-yarra': {
    slug: 'painters-in-south-yarra',
    name: 'South Yarra',
    region: 'Melbourne Inner',
    description: 'South Yarra\'s mix of luxury apartments, heritage terraces, and modern townhouses demands a painter with versatility and attention to detail. Norm Painting has extensive experience delivering premium finishes for South Yarra\'s discerning homeowners.',
    nearbyAreas: ['Toorak', 'Prahran', 'Windsor', 'Hawksburn', 'Richmond', 'St Kilda Road', 'Armadale'],
    image: '/projects/project-47.jpg',
    metaDescription: 'Professional painters in South Yarra. Luxury apartment, terrace, and townhouse painting with premium finishes — Norm Painting.',
  },
  'painters-in-richmond': {
    slug: 'painters-in-richmond',
    name: 'Richmond',
    region: 'Melbourne Inner',
    description: 'Richmond\'s iconic Victorian terraces and converted warehouses require a skilled painter who understands heritage surfaces. Norm Painting brings specialist knowledge in period home painting, timber restoration, and premium interior finishes to every Richmond property.',
    nearbyAreas: ['Cremorne', 'Abbotsford', 'Collingwood', 'Hawthorn', 'South Yarra', 'East Melbourne', 'Burnley'],
    image: '/projects/project-02.jpg',
    metaDescription: 'Painters in Richmond Melbourne. Victorian terrace and heritage home specialists with free quotes — Norm Painting.',
  },
  'painters-in-st-kilda': {
    slug: 'painters-in-st-kilda',
    name: 'St Kilda',
    region: 'Melbourne Inner',
    description: 'St Kilda\'s vibrant mix of Art Deco apartments, Edwardian homes, and modern residences needs a painter with broad expertise. We work across all property types in St Kilda, delivering crisp, lasting finishes that stand up to the coastal environment.',
    nearbyAreas: ['St Kilda East', 'Elwood', 'Balaclava', 'Ripponlea', 'Brighton', 'Port Melbourne', 'Albert Park'],
    image: '/projects/project-34.jpg',
    metaDescription: 'Painters in St Kilda. Art Deco, Edwardian, and modern home painting near the beach — Norm Painting.',
  },
  'painters-in-hawthorn': {
    slug: 'painters-in-hawthorn',
    name: 'Hawthorn',
    region: 'Melbourne East',
    description: 'Hawthorn\'s grand period homes and tree-lined streets are some of Melbourne\'s most prestigious. Norm Painting is trusted by Hawthorn homeowners for meticulous preparation, heritage-appropriate colour advice, and finishes that do justice to these beautiful properties.',
    nearbyAreas: ['Hawthorn East', 'Camberwell', 'Glen Iris', 'Kew', 'Richmond', 'Burnley', 'Toorak'],
    image: '/projects/project-15.jpg',
    metaDescription: 'Painters in Hawthorn Melbourne. Period home specialists with heritage colour advice and 7-year warranty — Norm Painting.',
  },
  'painters-in-brighton': {
    slug: 'painters-in-brighton',
    name: 'Brighton',
    region: 'Melbourne Bayside',
    description: 'Brighton\'s premium bayside properties deserve premium painting. From grand Edwardian homes to contemporary beachside residences, Norm Painting delivers flawless interior and exterior finishes that protect your investment and enhance your home\'s beauty.',
    nearbyAreas: ['Brighton East', 'Sandringham', 'Hampton', 'Bayside', 'Beaumaris', 'Mentone', 'Cheltenham'],
    image: '/projects/project-22.jpg',
    metaDescription: 'Painters in Brighton Melbourne. Premium bayside property painting, interior & exterior, with free quotes — Norm Painting.',
  },
  'painters-in-fitzroy': {
    slug: 'painters-in-fitzroy',
    name: 'Fitzroy',
    region: 'Melbourne Inner',
    description: 'Fitzroy\'s characterful terraces, Victorian cottages, and converted warehouses are among Melbourne\'s most loved properties. We bring careful preparation and premium finishes to every Fitzroy property, preserving its character while giving it a fresh new look.',
    nearbyAreas: ['Fitzroy North', 'Collingwood', 'Carlton', 'Clifton Hill', 'Brunswick', 'Northcote', 'Abbotsford'],
    image: '/projects/project-08.jpg',
    metaDescription: 'Painters in Fitzroy Melbourne. Victorian terrace and warehouse painting specialists — Norm Painting.',
  },
  'painters-in-camberwell': {
    slug: 'painters-in-camberwell',
    name: 'Camberwell',
    region: 'Melbourne East',
    description: 'Camberwell is home to some of Melbourne\'s finest family homes. Norm Painting is trusted by Camberwell homeowners for our thorough preparation, premium products, and the quality workmanship that comes with 10+ years of experience across the eastern suburbs.',
    nearbyAreas: ['Canterbury', 'Glen Iris', 'Balwyn', 'Hawthorn East', 'Box Hill South', 'Ashburton', 'Hartwell'],
    image: '/projects/project-25.jpg',
    metaDescription: 'Painters in Camberwell Melbourne. Family home painting specialists in Melbourne\'s eastern suburbs — Norm Painting.',
  },
  'painters-in-box-hill': {
    slug: 'painters-in-box-hill',
    name: 'Box Hill',
    region: 'Melbourne East',
    description: 'Box Hill\'s diverse mix of period homes, new builds, and commercial properties keeps Norm Painting busy across the area. Whether you need a full interior repaint or a commercial fit-out, our team delivers consistent quality on every job.',
    nearbyAreas: ['Box Hill North', 'Box Hill South', 'Mont Albert', 'Surrey Hills', 'Blackburn', 'Nunawading', 'Mitcham'],
    image: '/projects/project-11.jpg',
    metaDescription: 'Painters in Box Hill Melbourne. Residential and commercial painting in Melbourne\'s east — Norm Painting.',
  },
  'painters-in-doncaster': {
    slug: 'painters-in-doncaster',
    name: 'Doncaster',
    region: 'Melbourne East',
    description: 'Doncaster\'s leafy streets and quality family homes are a pleasure to work in. Norm Painting serves Doncaster and surrounds with interior and exterior painting, colour consultation, and the kind of workmanship that earns referrals from every client.',
    nearbyAreas: ['Doncaster East', 'Templestowe', 'Bulleen', 'Warrandyte', 'Park Orchards', 'Ringwood', 'Mitcham'],
    image: '/projects/project-03.jpg',
    metaDescription: 'Painters in Doncaster Melbourne. Quality residential painting in the north-east suburbs — Norm Painting.',
  },
  'painters-in-frankston': {
    slug: 'painters-in-frankston',
    name: 'Frankston',
    region: 'Melbourne South-East',
    description: 'Frankston and the Mornington Peninsula are growing fast, with new homes and renovations on every street. Norm Painting is your trusted local painting contractor — delivering fast, quality results for new builds, renovations, and full repaints throughout the area.',
    nearbyAreas: ['Frankston South', 'Langwarrin', 'Seaford', 'Carrum Downs', 'Karingal', 'Skye', 'Mornington'],
    image: '/projects/project-17.jpg',
    metaDescription: 'Painters in Frankston & Mornington Peninsula. New builds, renovations & repaints with free quotes — Norm Painting.',
  },
  'painters-in-dandenong': {
    slug: 'painters-in-dandenong',
    name: 'Dandenong',
    region: 'Melbourne South-East',
    description: 'Dandenong and the south-east corridor have a high demand for both residential and commercial painting. Norm Painting services the entire area with reliable, high-quality painting that meets every budget and timeline.',
    nearbyAreas: ['Noble Park', 'Springvale', 'Keysborough', 'Lyndhurst', 'Hallam', 'Narre Warren', 'Berwick'],
    image: '/projects/project-20.jpg',
    metaDescription: 'Painters in Dandenong & south-east Melbourne. Residential and commercial painting with free quotes — Norm Painting.',
  },
  'painters-in-footscray': {
    slug: 'painters-in-footscray',
    name: 'Footscray',
    region: 'Melbourne West',
    description: 'Footscray is one of Melbourne\'s most exciting and rapidly evolving suburbs. With a mix of Victorian workers cottages, new apartments, and commercial spaces, there\'s always painting to be done. Norm Painting delivers quality finishes for every property type in Footscray and the inner west.',
    nearbyAreas: ['Seddon', 'Yarraville', 'Sunshine', 'Maribyrnong', 'Flemington', 'Kensington', 'Newport'],
    image: '/projects/project-16.jpg',
    metaDescription: 'Painters in Footscray & inner west Melbourne. Residential and commercial painting — Norm Painting.',
  },
  'painters-in-werribee': {
    slug: 'painters-in-werribee',
    name: 'Werribee',
    region: 'Melbourne West',
    description: 'Werribee and the outer west are booming with new housing estates and established family homes. Norm Painting is your reliable painting contractor for new builds, renovations, and full repaints across Werribee and surrounding suburbs.',
    nearbyAreas: ['Hoppers Crossing', 'Wyndham Vale', 'Manor Lakes', 'Point Cook', 'Laverton', 'Altona', 'Williamstown'],
    image: '/projects/project-23.jpg',
    metaDescription: 'Painters in Werribee & Wyndham. New home and renovation painting in Melbourne\'s outer west — Norm Painting.',
  },
  'painters-in-point-cook': {
    slug: 'painters-in-point-cook',
    name: 'Point Cook',
    region: 'Melbourne West',
    description: 'Point Cook\'s modern housing estates and growing community make it one of Melbourne\'s most in-demand areas for painting services. Norm Painting works with new homeowners and renovators throughout Point Cook to deliver fresh, lasting finishes.',
    nearbyAreas: ['Werribee', 'Hoppers Crossing', 'Sanctuary Lakes', 'Williams Landing', 'Altona Meadows', 'Laverton'],
    image: '/projects/project-35.jpg',
    metaDescription: 'Painters in Point Cook Melbourne. New home and renovation painting in Wyndham\'s fastest-growing suburb — Norm Painting.',
  },
  'painters-in-glen-waverley': {
    slug: 'painters-in-glen-waverley',
    name: 'Glen Waverley',
    region: 'Melbourne South-East',
    description: 'Glen Waverley\'s quality family homes and growing commercial precinct keep Norm Painting busy year-round. We deliver premium interior and exterior painting with careful preparation, premium products, and a finish that adds real value to your property.',
    nearbyAreas: ['Mount Waverley', 'Wheelers Hill', 'Mulgrave', 'Notting Hill', 'Brandon Park', 'Rowville', 'Scoresby'],
    image: '/projects/project-42.jpg',
    metaDescription: 'Painters in Glen Waverley Melbourne. Quality residential and commercial painting in the south-east — Norm Painting.',
  },
};
